modLoader = "javafml"
license = "ARR"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/Oh-My-Sherd/issues"

[[mods]]
modId = "ohmysherd"
version = "26.2.0.0"
displayName = "OhMySherd"
updateJSONURL = "https://updates.blamejared.com/get?n=ohmysherd&gv=26.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/oh-my-sherd"
logoFile = "logo_ohmysherd.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Keyana , Darkosto, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "New sherds for Minecraft!"

[[mixins]]
config = "ohmysherd.common.mixins.json"

[[mixins]]
config = "ohmysherd.neoforge.mixins.json"

[[dependencies.ohmysherd]]
modId = "minecraft"
type = "required"
versionRange = "26.2"
ordering = "NONE"
side = "BOTH"

[[dependencies.ohmysherd]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ohmysherd]]
modId = "bookshelf"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ohmysherd]]
modId = "prickle"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

